http:
  routers:
    prometheus:
      rule: "Host(`prometheus.primecloud.local`)"
      entryPoints:
        - websecure
      service: prometheus
      tls: {}


  services:
    prometheus:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: "http://10.10.30.30:9090"   # monitoring CT IP + Prometheus port
