http:
  routers:
    woodpecker:
      rule: "Host(`ci.primecloud.local`)"
      entryPoints:
        - websecure
      tls: {}
      service: woodpecker

  services:
    woodpecker:
      loadBalancer:
        servers:
          - url: "http://10.10.30.40:8000"
